tasks:
  - name: Compilation
    init: |
      make
      gp sync-done make
    command: rails server
  - name: The Myth of Blob
    openMode: tab-after
    init: gp sync-await make
    command: ./blobmyth
